#!/bin/bash
# vim: ts=4 expandtab

DEBEMAIL="Cliff Moon <cliff@fastip.com>"
RELEASE=""
DISTRO=karmic

# from 
# http://blog.loftninjas.org/?p=248

if [ $# -le 1 ]; then
    echo "Usage: $0 <URL to .gem or .tar.gz>  [ <package name> ]" >&2
    echo "Generate a .deb package from a ruby .gem (or gem as .tar.gz)" >&2
    exit 1
fi

URL="$1"

set -x

origpath=$( pwd )
trap "cd '$origpath' && test -d '$WORKDIR' && rm -rf '$WORKDIR'" EXIT

WORKDIR=$( mktemp -t -d gm2db.XXXXXXXXXX )

if [ $? -ne 0 -o ! -d "$WORKDIR" ]; then
    echo "$0: unable to create temporary directory" >&2
    exit 1
fi

cd $WORKDIR
filename=`gem fetch "$1" | awk '{print $2}'`
gem unpack "$filename.gem"
basedir=$(basename $filename)

cd "$basedir"
cp /usr/lib/ruby/1.8/setup.rb .
mkdir debian
BD=$( pwd )
VERSION=$( basename $BD | perl -pe 's/^.+-([\d.]+)$/$1/;' )
PACKAGE=$( basename $BD | perl -pe 's/^(.+)-[\d.]+$/$1/;' )

GEM_DEPENDENCIES=`gem dependency "$1" | grep runtime | sed 's/ *\(\w*\) (\(.*\), runtime)/lib\1-ruby1.8 (\2)/' | \
  tr '\n_' ',-' | sed 's/,$//' | sed 's/~>/>=/g'`
echo $GEM_DEPENDENCIES
if [ -d ext ]; then
  ARCHITECTURE=`uname -m | sed s/x86_64/amd64/`
else
  ARCHITECTURE=all
fi

# we don't want to edit the changelog file after generation
# so make /usr/bin/sensible-editor attempt to use /bin/true as the editor
EDITOR=/bin/true
VISUAL=/bin/true
export EDITOR VISUAL

if [ -z "$2" ]; then
    PACKAGE=lib$PACKAGE-ruby
else
    PACKAGE="$2"
fi

if [ -z $DEPENDENCIES ]; then
  DEPLIST="$GEM_DEPENDENCIES"
else
  DEPLIST="$GEM_DEPENDENCIES, $DEPENDENCIES"
fi

dch --create "-v$VERSION-$RELEASE" -D $DISTRO --package "$PACKAGE" 'initial release'


cat > debian/rules <<EOF
#!/usr/bin/make -f

include /usr/share/cdbs/1/rules/simple-patchsys.mk
include /usr/share/cdbs/1/rules/debhelper.mk
# Ruby package with setup.rb
include /usr/share/ruby-pkg-tools/1/class/ruby-setup-rb.mk
EOF
chmod ugo+rx debian/rules

cat > debian/control <<EOF
Source: $PACKAGE
Section: libs
Priority: optional
Maintainer: No One
Build-Depends: cdbs, debhelper (>> 5.0.0), ruby-pkg-tools, ruby1.8
Standards-Version: 3.8.0

Package: $PACKAGE
Architecture: $ARCHITECTURE
Depends: ruby1.8, $DEPLIST
Description: the $PACKAGE ruby gem

Package: $PACKAGE-doc
Section: doc
Architecture: all
Description: documentation for the $PACKAGE ruby gem
 .
 This is the documentation package, with upstream documentation as well as
 generated rdoc.
EOF

dpkg-buildpackage -rfakeroot

cd $origpath
mkdir -p $PACKAGE
cp $WORKDIR/$PACKAGE* $PACKAGE/
ls -l $PACKAGE/*

#rm -rf "$WORKDIR"

